### ISSUE TITLE
Factures : problème génération avoirs sur SCC et incohérences

### ISSUE THREAD

**Issue by clairewebportage** [B3Software/scx.upnbiz.com#450]
Facture 8217 (CORA Patricia, portée SCC) notée comme annulée mais aucun avoir généré et donc non comptabilisé

TODO:
- [x] voir ce qui s'est passé
- [x] voir si d'autres sont dans le même cas
- [x] corriger
- [x] prévenir Claire
- [x] voir avoir Allot
- [x] prendre pour dates de la prestation de l'avoir les dates de la facture qu'il annule (valable pour SC et WP) - fait au ticket #470 
- [ ] générer les avoirs pour les [factures supprimées sans avoir associé](https://github.com/B3Software/sud-convergences/issues/450#issuecomment-35719281)
- [x] regénérer les PDF qui n'ont pas été générés ([avoirs](https://github.com/B3Software/sud-convergences/issues/450#issuecomment-36726707) et [factures](https://github.com/B3Software/sud-convergences/issues/450#issuecomment-36739757))
- [x] prévenir Claire et Marylène
- [x] Nouveaux cas (ROSS) ligne dans comptes portes mais pas dans facture
